---
# Install repository
- include_tasks: "install_repository_for_{{ ansible_os_family|lower }}.yml"
# Install server and set up (user) and group
- include_tasks: install_package.yml
# Install cli
- import_tasks: install_cli.yml
# Install/Update plugins
- include_tasks: install_plugins.yml
  when: jenkins_plugins|length > 0
