---
# Ubuntu LTS 12.04 version is out of date, therefore the updating to use
# http://pkg.jenkins-ci.org/debian/

# Add Jenkins repository key
- name: install debian | ensure jenkins apt-key exists
  apt_key:
    url: http://pkg.jenkins.io/debian-stable/jenkins.io.key
    state: present
  tags:
    - jenkins
    - install
    - repository

# Add Jenkins repository
- name: install debian | ensure jenkins debian repository exists
  apt_repository:
    repo: 'deb http://pkg.jenkins.io/debian-stable binary/'
    state: present
  tags:
    - jenkins
    - install
    - repository
